### ISSUE TITLE
Achievement gfx for Husk items

### ISSUE THREAD

**Issue by basketini-jones** [basketini-jones/duke#107]
Can't do them right now since I don't have my tablet so I'll put this here as a reminder

**Comment by ngregrichardson** [comment]
@basketini-jones Some of the older ones that have been renamed need to be updated as well.

**Comment by basketini-jones** [comment]
- Change Hollow Heart to Infested Heart
- Make Fiendish Swarm look better
- Add The Invader, Duke of Eyes, Red Tapeworm Card, Mosquito, Soul of Duke, Fly Hearts
