### ISSUE TITLE
Add support for Rep+ modded hearts

### ISSUE THREAD

**Issue by ngregrichardson** [basketini-jones/duke#115]
**Working Pickup and Fly Granting**
- [x] Broken Heart
- [x] Dauntless Heart
- [x] Hoarder Heart
- [x] Deceiver Heart
- [x] Soiled Heart
- [x] Curdled Heart
- [x] Savage Heart
- [x] Benighted Heart
- [x] Enigma Heart
- [x] Capricious Heart
- [x] Baleful Heart
- [x] Harlot Heart
- [x] Miser Heart
- [x] Empty Heart
- [x] Fettered Heart
- [x] Zealot Heart
- [x] Deserter Heart

**Comment by basketini-jones** [comment]
https://docs.google.com/document/d/1ji7a2SL5rY2qTm7Sm4MwEoIuQf-6rIgcKCmMrCgs8yQ/edit?usp=sharing

**Comment by ngregrichardson** [comment]
All hearts still need Husk support and fly and spider implementations
