### ISSUE TITLE
Pickup prices -5 and -6 should not convert into fly prices

### ISSUE THREAD

**Issue by ngregrichardson** [basketini-jones/duke#117]
Squigs

**Comment by basketini-jones** [comment]
To test price -5:
1. Give yourself A Pound of Flesh (item)
2. Go to any shop. Pickups will cost price -5 (Items will cost Devil price -1 through -4)

To test price -6:
1. Give yourself Your Soul (trinket)
2. Go to any devil room. The items will cost price -6
