### ISSUE TITLE
Create unlocks system for unlocking achievements

### ISSUE THREAD

**Issue by basketini-jones** [basketini-jones/duke#16]
> ideas for character unlocks

**Changed to**: Create unlocks system for unlocking achievements

**Comment by basketini-jones** [comment]
Mom's Heart: Duke Baby (Co-op Baby) - Shoots Heart Attack Flies instead of tears
Boss Rush: Lil' Duke (Familiar) - Orbits Isaac and blocks bullets. Spawns a random Heart Attack Fly after blocking a bullet.
Isaac: Duke's Tooth (Trinket) - At the start of every room with enemies, spawn a random Heart Attack Fly.
Satan: Hollow Heart (Trinket) - All hearts picked up have a 50% chance to become Heart Orbital Flies.
???: Duke's Gullet (Active - 1 Room) - As a normal player, spawns 2 random Heart Attack Flies. As Duke's pocket active, turns all of his current Heart Orbital Flies into Heart Attack Flies.
The Lamb: The Princes (Passive) - At the start of every new floor, gain 3 random Heart Orbital Flies.
Mega Satan: Husk Baby (Co-op Baby) - Occasionally spawns Pickup Spiders while firing (lets not work on this guy until Tainted Duke)
Hush: Super Infestation (Passive) - On damage taken, whatever hearts you lose get turned into Heart Orbital Flies.
Greed: Tapeword Card (Card) - On use, turns all enemies in the room into Heart Orbital Flies.
Greedier: Sharty McFly (Familiar) - On room entry, spawns a Charmed Poop in a random location. Enemies will target the Charmed Poop.
Mother: Fiendish Swarm (Active - 2 Room) - On use, lose all HP down to 1 full heart. All health lost in this way becomes Heart Orbital Flies. At the end of the room, all the Heart Orbital Flies gained turn back into the player's health.
Beast: Queen Fly (Passive) - All Blue Flies gained turn into random Heart Attack Flies. Basic Fly enemies turn into Heart Orbital Flies.
Delirium: Duke Flute (Active - 6 Room) - Summons a friendly Duke of Flies, who bounces around the room dealing contact damage and spawns Charmed Fly enemies for 10 seconds.
All Completion Marks: Swarm Baby (Co-op Baby) - Tears will occasionally have Dark Matter, Eye of Greed, Compound Fracture, or Scorpio effect.

**Comment by ngregrichardson** [comment]
Separate issues made:

#37 
#38 
#39 
#40 
#41 
#42 
#43 
#44 
#45 
#46 
#47 
#48 
#49

Transformed this issue in to the unlock system issue.
