### ISSUE TITLE
Fiendish Swarm (Active - 2 Room)

### ISSUE THREAD

**Issue by ngregrichardson** [basketini-jones/duke#46]
On use, lose all HP down to 1 full heart. All  health lost in this way becomes Heart Orbital Flies. At the end of the room, all the Heart Orbital Flies gained turn back into the player's health.

**Comment by ngregrichardson** [comment]
We gotta talk about this one friend

**Comment by basketini-jones** [comment]
The AlGoRiThM:

- If the player has 1 or more Heart Containers and 1/2 or more Red Hearts, bring them down to half a Red Heart and remove all other heart types.
- If the player has no Red Hearts and 1/2 or more Soul Hearts, bring them down to half a Soul Heart and remove all other Heart Types. Empty Heart Containers and Bone Hearts do not matter. If a Bone Heart is in the first position, remove it anyway.
- If the player has no Heart Containers and no Soul Hearts (i.e. only Bone Hearts), bring them down to 1 Bone Heart.
- Black Hearts count as Soul Hearts for all above conditions.
- Rotten Hearts count as Red Hearts for all above conditions. If a player only has Rotten Hearts with no Red Hearts, we'll bring them down to 1/2 Red Heart anyway.
