### ISSUE TITLE
Tainted Duke / The Husk Mechanics

### ISSUE THREAD

**Issue by basketini-jones** [basketini-jones/duke#51]
Starts with 2 Soul HP and can fly like Duke, and has 2 Red Heart Spiders.

Starting item: Rotten Gullet

Rotten Gullet starts with 1 Heart Counter (like Jar of Flies, it has the little x1 number next to it).

Picked up hearts get added to the Rotten Gullet counters, which maxes out at x24

On use, Rotten Gullet consumes a counter and fires 8 tears in all directions. The tears have effects based on the Heart Container it consumes, and each bullet has a 50% chance of spawning a corresponding Heart Spider.

Heart Spiders have identical effects to Heart Attack Flies, but they move like Blue Spiders.

Heart Counters are consumed in a FIFO order.

**Comment by basketini-jones** [comment]
Tear Effects for each Heart Type:
- Red Heart: 1.5x damage
- Soul Heart: 1.5x damage
- Eternal Heart: 4.0x damage, piercing
- Black Heart: 2.0x damage, necronomicon effect on use
- Gold Heart: 1.5x damage, Midas Touch effect on colliding with enemies
- Bone Heart: 2.0x damage, compound fracture tear effect
- Rotten Heart: 1.5x damage, spawn Blue Fly on colliding with enemies
- Broken Heart: Nothing, takes up 2 counter spots permanently and cannot be consumed

Heart Spiders:
- Red Heart Spider: Default
- Blue Heart Spider: Default
- Eternal Heart Spider: 1.5x damage, Creates a Holy Light Beam on death
- Black Heart Spider: 1.3x damage, frighens enemy on collision
- Gold Heart Spider: Drops a coin on death
- Bone Heart Spider: 1.3x damage, Drops a bone spur on death
- Rotten Heart Spider: Poisons enemy on collision

**Comment by ngregrichardson** [comment]
huskers
