### ISSUE TITLE
Fly Hearts (Pickup)

### ISSUE THREAD

**Issue by basketini-jones** [basketini-jones/duke#55]
Hearts have a chance of becoming Fly Hearts, which spawn their corresponding Heart Fly Orbitals as well as healing the player for that much.
Hopefully we don't have to make custom entity subtypes for every heart in existence. Maybe we can just add a data tag to existing hearts that makes them into Fly Hearts. If we can't, lets just do something else entirely.
Unlock: Defeat Mega Satan as Husk

**Comment by ngregrichardson** [comment]
@basketini-jones What is the chance that this happens?

**Comment by basketini-jones** [comment]
Let's say 5% chance to replace the normal heart type
